### ISSUE TITLE
Initial install dependencies never completes, no UI feedback

### ISSUE THREAD

**Issue by ryanjbonnell** [valet-lite/beta#13] opened 2020-10-08 22:08 UTC
When attempting to installing Valet Lite for the first time, the step to _Install dependencies_ never completes — no UI feedback is shown and attempting to invoke the Log menu doesn't do anything.

![Screen Shot 2020-10-08 at 3 11 58 PM](https://user-images.githubusercontent.com/133372/95518859-d0476f00-0978-11eb-99d1-adde514f31e8.png)

Tested using Valet Lite 0.1.30 (0.1.30) on macOS "Catalina" 10.15.7 (19H2).

**Comment by ryanjbonnell** [comment] 2020-10-08 22:20
This issue appears to be a by-product of https://github.com/valet-lite/beta/issues/5

**Comment by davidhemphill** [comment] 2020-10-08 22:49
Duplicate of #3. I sent a second email today with the proper download links. 😄

**Closed by davidhemphill** 2020-10-08 22:49 UTC
