### ISSUE TITLE
Stuck on "Install dependencies"

### ISSUE THREAD

**Issue by martin-ro** [valet-lite/beta#11] opened 2020-10-08 20:55 UTC
I start the app, hit Install dependencies, type my password and nothing happens. Also no network activity - so I guess it is not installing anything?

Catalina 10.15.4

**Comment by davidhemphill** [comment] 2020-10-08 21:58
Duplicate of #3

**Comment by davidhemphill** [comment] 2020-10-08 21:58
I sent a second email today with the proper download links. 😄

**Closed by davidhemphill** 2020-10-08 21:58 UTC
