### ISSUE TITLE
Loading indicator while installing dependencies

### ISSUE THREAD

**Issue by andypa** [valet-lite/beta#8] opened 2020-10-08 15:23 UTC
I started Valet Lite and clicked "Install dependencies" and waited for around 10 minutes but I don't see any network activity in the activity manager. It would be great to see if the dependencies are being installed or some kind of loading indicator.

Best regards,
Andy

**Comment by davidhemphill** [comment] 2020-10-08 15:31
Hi! This looks like a duplicate of #3

**Comment by davidhemphill** [comment] 2020-10-08 15:31
Make sure you grab the newest link from the second email I sent today! It contains all of the dependencies.

**Closed by davidhemphill** 2020-10-08 15:31 UTC
